# Use the official PHP image as the base image
FROM php:7.4-apache

# Set the working directory to /var/www/html
WORKDIR /var/www/html

RUN apt-get update && \
    apt-get install -y \
    libzip-dev \
    zip \
    unzip \
    git && \
    docker-php-ext-install pdo_mysql zip && \
    a2enmod rewrite

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY composer.json composer.lock /var/www/html/

RUN composer install --no-scripts --no-autoloader

COPY . /var/www/html

RUN composer dump-autoload --optimize

RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

EXPOSE 80

CMD ["apache2-foreground"]
